def menu():
    print("-"*50)
    print("Banking Information System")
    print("-"*50)
    print("\t1. Open An Account")
    print("\t2. PIN Generate")
    print("\t3. PIN Change")
    print("\t4. Deposit")
    print("\t5. Withdraw")
    print("\t6. Search for Customer")
    print("\t7. View Single Customer Details")
    print("\t8. View All Customers")
    print("\t9. Close Account")
    print("\t10. Exist")
