#Program for accessing Randoom Accessing the File Data
with open("D:\\Python\\Operations-On-File\\hyd.info","rt") as fp:
    print("Intially, file points tp:",fp.tell())
    filedata = fp.read(3)
    print("File Data =",filedata)
    print("Now, Position of fp =",fp.tell())
    filedata = fp.read(4)
    print("File Data =",filedata)
    print("now, position of fp =",fp.tell())
    filedata = fp.read(7)
    print("File data=",filedata)
    print("now,position of fp=",fp.tell())
    print("-"*50)
    filedata = fp.read()
    print("file data =",filedata)
    print("now, position of fp=",fp.tell())
    print("-"*50)
    fp.seek(7)
    print("now, position offp =",fp.tell())
    filedata = fp.read(7)
    print("File data =",filedata)
    print("now, positioni of fp =",fp.tell())
    print("-"*50)
    fp.seek(0)
    print("now, position of fp=",fp.tell())
    filedata = fp.read(10)
    print("now, position of fp=",fp.tell())

